### PR TITLE
Configure serial + vga consoles and disable blanking

### PR DESCRIPTION
**Pull request by lgrawet**
Hi,

Here are some settings I use to configure both serial (for virsh console) and vga (for vnc) consoles.
I also disable console blanking.

Best regards,

Laurent

### CODE REVIEW

**Comment by lgrawet** [comment]
Please also note that tty0 is recommended for this usage rather than tty1

> vc/0 (tty0) is just an alias for the current virtual terminal and it's where messages from the system are sent. Thus messages from the system will be seen on the console (monitor) regardless of which virtual terminal it is displaying.

See [Text Terminal Howto](http://tldp.org/HOWTO/Text-Terminal-HOWTO-7.html)
and [Remote Serial Console Howto](http://www.tldp.org/HOWTO/Remote-Serial-Console-HOWTO/configure-kernel.html)

**Comment by vholer** [comment]
Hi @lgrawet,

I'm still thinking about these changes and my feeling is that the contextualization package shouldn't care much about the configuration of components which can't be directly used by the OpenNebula. Although I understand the benefits of the serial console, this decision should be up to the user how he prepares the images and how he wants to use that. I have already removed from the post install script this reconfiguration https://github.com/OpenNebula/addon-context-linux/commit/198c46b48baba8425f92409cc8c2b0b7c642e529#diff-43eda34539b3226f7a0a23a74e0f83b7L83 .

About the console blanking, I like the idea. It would be better if it can be done without modifying the kernel boot parameters. I'll open a new issue to track the request.

Best regards,
Vlastimil

**Comment by lgrawet** [comment]
Hi Vlastimil,

And what about this one:
https://github.com/OpenNebula/addon-context-linux/pull/69/commits/e9950874dd0063c7318872b38f255055fa7c03e0

So the user can easily override some settings.

Best regards,

Laurent

**Comment by vholer** [comment]
Hi @lgrawet, for the start, I have added this script https://github.com/OpenNebula/addon-context-linux/commit/3d613abe06b0d85102a8a00f4d2a64779487a4e2 to disable console blanking without reconfiguring the kernel. We can improve it anytime. Best, Vlastimil

**Comment by vholer** [comment]
Closing this PR. Console blanking is disabled by context scripts, serial console is not oficially supported.

**Pull request closed without merging**
