### PR TITLE
B #3019: Remove securetty validation from pam

### PR DESCRIPTION
**Pull request by sergiojvg**

### CODE REVIEW

**Comment by vholer** [comment]
Why is this in Ruby, when all the rest scripts is pure shell?
How is suitable default for LXD (yes) and all the rest (no) ensured?

**Comment by sergiojvg** [comment]
Went through hell while expanding variables with special characters inside with sed, could not get it done. Ruby is a dependency in context packages, that is why I went with ruby.

About LXD and the others, I did not want to limit it. It is true right now this is only useful for LXD, but if anyone wants to use it with KVM machines, do not see a reason to avoid it.

**Comment by vholer** [comment]
> Went through hell while expanding variables with special characters inside with sed, could not get it done. Ruby is a dependency in context packages, that is why I went with ruby.

I confess that I probably don't see the hidden logic behind, but I thought the functionality could be like:

```
sed -i -e 's/^\([^#]*pam_securetty.*\)$/#\1/' /etc/pam.d/login
```

Plus, handling uncommenting back would be very nice to have.

Ruby dependency is only because of the OneGate client. I wouldn't mess context scripts with Ruby.

Maybe, the alternative solution would be also to simply rename `/etc/securetty` (-> `.bak`). But, it could be brought back by system update.

> About LXD and the others, I did not want to limit it. It is true right now this is only useful for LXD, but if anyone wants to use it with KVM machines, do not see a reason to avoid it.

Yes, the comment wasn't about limiting it only on LXD, but to set default values for `SECURETTY` (if it's not specified in the context variables). For LXD (yes, you would have to detect if it's container or VM), have default to **disable** securetty. For the rest, have default to **enable** securetty. And, user still can set `SECURETTY` context variable in the VM template for override.

**Comment by rsmontero** [comment]
:+1: to use shell script for commenting out the securetty line.

About the defaults we can set this in oned (when the CONTEXT attribute is genrated). In anycase, the script should set a default (do nothing if not set) to deal with previous versions of OpenNebula.

**Pull request merged**
