### PR TITLE
Set ${PASSWORD} for ${USERNAME}

### PR DESCRIPTION
**Pull request by baby-gnu**

### CODE REVIEW

**Comment by baby-gnu** [comment]
Hello,

I was not sure to fallback on `root` if `${USERNAME}` does not exist.

For the use case, when preparing an image for context, we define which user can do what, then the `${USERNAME}` is set directly in the template and `${PASSWORD}` as a user input.

We have a custom, per distrib, context script which do whatever needed to create `${USERNAME}` and set sudo authorization.

Regards.

**Comment by baby-gnu** [comment]
Hello,

Is there anything missing to make this pull request mergeable?

Regards.

**Comment by jfontan** [comment]
I think the patch is OK but maybe I would also add a `CRYPTED_PASSWORD` or something similar in case someone doesn't want it plain in the VM information. I'll merge this now.

Thank you and sorry for the delay.

**Comment by baby-gnu** [comment]
+1

I'll handle the CRYPTED_PASSWORD soon and make a pull request.

Regards.

**Pull request merged**
