### PR TITLE
Arch one-context support

### PR DESCRIPTION
**Pull request by dkelleher**
Adding arch support for one-context scripts.  Let me know what you think.  I edited the init.d script and made it into a simple executable so that I could use a systemd unit to call it.  I edited the 00-network file to work with systemd-networkd. I also moved the init.d script since arch doesn't use it.

### CODE REVIEW

**Comment by jfontan** [comment]
I like the changes and the idea of moving startup script from SysV script to another file. If the functionality is the same maybe we can put this file in /usr/sbin/vmcontext and call it from systemd and SysV scripts.

Also it would be good to add a PKGBUILD file and some documentation on how to install it. Do you think it is easy to add this to AUR?

Thanks!

**Comment by dkelleher** [comment]
The functionality should be the same and I'll move it to sbin.  I'm working on making a PKGBUILD which should be very simple and I did intend to add it to the AUR.  I want to work on the systemd service a bit, it appears to be running to early in the startup sometimes so I have to figure out what other targets I need to add so that it's more robust.

**Comment by dkelleher** [comment]
Added a bunch more.  I'm going to write some systemd scripts for the RPM and Deb packages.  Also some testing with libcloud next week.

**Comment by dkelleher** [comment]
@jfontan This should be all set for your review.  I intend to push the PKGBUILD info to the AUR once I can point it at the OpenNebula github instead of FASRC

**Comment by jfontan** [comment]
Great, thank you! I'll ping you as soon as I have reviewed the changes.

**Comment by jfontan** [comment]
Why is package `cloud-utils-bzr` required? It is giving me errors with keys and adds a lot of dependencies.

If only `growpart` is used I got it installed with package `mkinitcpio-growrootfs`.

**Comment by dkelleher** [comment]
Great find I'll update that I had only found growpart in cloud-utils

**Comment by jfontan** [comment]
Tested both rpm and deb packages. Everything seems to be working ok. Merging to master.

This will be released as 4.14.2. Thank you!

**Pull request merged**
